id: php-composer-test-wiki-policy
name: Private PHP repos _must_ have wiki disabled
subject: repository
filters:
  - resource.name.startsWith("php")
  - resource.isPrivate == true
constraints:
  - resource.hasWikiEnabled == true
